//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstronomyClassTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articles()
        {
            this.Tests = new HashSet<Tests>();
        }
    
        public int id { get; set; }
        public int id_teacher { get; set; }
        public string name_article { get; set; }
        public int id_type { get; set; }
        public string weight { get; set; }
        public string size { get; set; }
        public string distance { get; set; }
        public string description { get; set; }
        public string text_article { get; set; }
        public System.DateTime date_create_article { get; set; }
        public byte[] image { get; set; }
        public bool active { get; set; }
    
        public virtual ArticleTypes ArticleTypes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tests> Tests { get; set; }
    }
}
